### ISSUE TITLE
[BUG] Major graphical glitches in Firestarter

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#12] opened 2020-02-02 08:17 UTC
**Describe the bug**
If you're seeing a visual bug, a screenshot is much better than written explaination

**To Reproduce**
1. Play 'Firestarter' up until the break.
2. A flickering triangle appears on the blue track, leading to a "diagonal" crossfade and ending the chart early

**Expected behavior**
The chart would continue as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/4022196/73605274-e1c2b680-4561-11ea-9daf-0456963ffb03.png)

(using custom graphics)
![image](https://user-images.githubusercontent.com/4022196/73605238-4e898100-4561-11ea-8bcf-2df99d4c15de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903

**Comment by jummy0** [comment] 2020-02-02 08:46
Tried out a few other charts as well. Seems to only happen on a crossfade from right to center. No other chart has caused the "diagonal" crossfade yet, but the flickering triangles are pretty common. Daft Mouth has this happen a few times, and it can cause blue notes to be "stuck" in the right crossfade position.
![image](https://user-images.githubusercontent.com/4022196/73605619-10429080-4566-11ea-8942-8e832626617b.png)
![image](https://user-images.githubusercontent.com/4022196/73605624-19336200-4566-11ea-8544-ada96e962866.png)

**Comment by MatteoGodzilla** [comment] 2020-02-03 07:21
Looked into that and it's caused by missing crossfades caused by poor parsing of file.
And all of the graphical glitches I saw were for this reason.

**Comment by MatteoGodzilla** [comment] 2020-02-06 05:50
Fixed with update 1.1

**Closed as completed by MatteoGodzilla** 2020-02-06 05:50 UTC
Labels: bug
